set(_CATKIN_CURRENT_PACKAGE "filtro_particulas_simples")
set(filtro_particulas_simples_MAINTAINER "au <au@todo.todo>")
set(filtro_particulas_simples_DEPRECATED "")
set(filtro_particulas_simples_VERSION "0.0.0")
set(filtro_particulas_simples_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(filtro_particulas_simples_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(filtro_particulas_simples_BUILDTOOL_DEPENDS "catkin")